spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_temp2?createDatabaseIfNotExist=true
    username: root
    password: 6886375
  jpa:
    hibernate:
      ddl-auto: create




